
CREATE OR REPLACE VIEW TF_DATA_WAREHOUSE.SALES_AND_MARKETING.NX_SUBACCOUNT_ACTIVATES
AS

SELECT 
"EVENT_DATE" AS "DATE",
CASE WHEN "PRODUCT_CATEGORY" IS NULL 
	THEN 'Unknown' ELSE "PRODUCT_CATEGORY" 
		END AS "PRODUCT", 
CASE WHEN "PRODUCT_SEGMENT" IS NULL 
    THEN 'Unknown' ELSE "PRODUCT_SEGMENT" 
        END AS "PRODUCTAREA",
*        
FROM TF_NEXCESS.PUBLIC.TRANSACTION_MRIC_FACT mf
WHERE "EVENT" = 'Subaccount.Status.Activate'
AND "EVENT_DATE" >= '2020-01-01'
ORDER BY "EVENT_DATE" DESC;
